### ISSUE TITLE
Error entrando a jugar

### ISSUE THREAD

**Issue by ghost** [bombermanxtreme/bombermanxtreme#3]
![error entrando a juego](https://user-images.githubusercontent.com/17006012/33673679-6dfc3a3a-da7b-11e7-8306-9cd12a09dba2.png)
![consola 1](https://user-images.githubusercontent.com/17006012/33673718-96cc65de-da7b-11e7-954f-e0696bc75b55.png)
![consola 2](https://user-images.githubusercontent.com/17006012/33673719-96f25dc0-da7b-11e7-8814-130ba8211309.png)

**Comment by ghost** [comment]
espero le sirva de algo, ahí le mando la consola y la del navegador @KevinSSP un abrazo

**Comment by KevinSSP** [comment]
Ya no se utiliza lectura de archivo... se definieron unos tableros con string[][] dentro la propia clase.
